### ISSUE TITLE
suitest automated exits with success even when some devices fail

### ISSUE THREAD

**Issue by onlynone** [SuitestAutomation/suitest-js-api#399]
I noticed that when I run `suitest automated`, if at least one device passes the tests, then the process will exit with a successful exit code. It will only exit with a failure if all the devices in the test pack fail,

I think this is due to the line:

https://github.com/SuitestAutomation/suitest-js-api/blob/b12e5a6dabd97345ddf5fc03db44b0453d6f3897/lib/utils/testLauncherHelper.js#L399

In this code, it looks like `failedDevices.length` will be the number of failed devices, and `result.length` will be the total number of devices. As such, `handleChildResult` will only be called with `finishedWithErrors=true` when the number of failed devices is greater than or equal to the total number of devices.

I think it should be changed to:

     handleChildResult(failedDevices.length > 0);

**Comment by polomsky** [comment]
Fixed in 4295692209f5120cbc36cca80995a95850495980
