### ISSUE TITLE
Launcher doesn't call close session

### ISSUE THREAD

**Issue by radimbuchtela** [SuitestAutomation/suitest-js-api#451]
https://github.com/SuitestAutomation/suitest-js-api/blob/4b1ff32d6cddcd0bdca5675ebb9b6f8e134dc79b/lib/testLauncher/SuitestLauncher.js#L111

It seems the launcher doesn't call `closeSession` in finally-block after the test is finished. It happens because `process.exit()` is executed in previous step inside `runAllDevices` function.

Please, could you check it?

**Comment by polomsky** [comment]
Fixed by #453 .
