### ISSUE TITLE
ISuitest type definition should include LAUNCH_MODE

### ISSUE THREAD

**Issue by onlynone** [SuitestAutomation/suitest-js-api#452]
The docs indicate that the `suitest` object should contain `LAUNCH_MODE.RESUME` and `LAUNCH_MODE.RESTART`: https://suite.st/docs/suitest-api-v2/test-operations/#openapp But the `ISuitest` interface defined in `index.d.ts` does not contain a `LAUNCH_MODE` property.

**Comment by polomsky** [comment]
Fixed by #455 and #456.
