### ISSUE TITLE
Type description of query results should be potentially undefined, not void

### ISSUE THREAD

**Issue by onlynone** [SuitestAutomation/suitest-js-api#459]
The type descriptions for a lot of query results are defined like:

```
type ElementQueryResult = ElementProps | void;
```

I think those should be:
```
type ElementQueryResult = ElementProps | undefined;
```

I think the type `void` is only really used for functions that don't return anything, not for an actual object.

When I use a typeguard like lodash's `isNil` on the result, it's not enough to narrow the type to just `ElementProps` since `void` isn't even `null | undefined`. A current work-around is to use `isObject`.

[The documentation](https://suite.st/docs/suitest-api-v2/chain-types/#element) even says, "If the element is not found then undefined will be returned."

I'm guessing all the instances of `someType | void` in the type definitions should be changed to something else (probably `undefined`).

**Comment by polomsky** [comment]
Fixed in version 3.6.1.
